# Configuration for Travis CI.

language: php
php:
  - 5.5
  - 5.6
  - 7.0

services:
  - mysql

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

install:
  # Save the module directory to a variable.
  - MODULE_DIR=$(pwd)

  # Export the composer bin folder.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Download drush to help with site installation and enabling the module.
  - composer global require drush/drush
  - phpenv rehash
  - cd ..

  # Download a fresh Drupal 8 installation.
  - drush dl drupal-8 --drupal-project-rename=drupal
  - cd drupal

  # Install the Drupal 8 site.
  - drush site-install --verbose --db-url=mysql://root:@127.0.0.1/test --yes

  # Symlink the Import API module to Drupals modules directory.
  - ln -s $MODULE_DIR ./modules/import_api

  # Enable the Import API module.
  - drush en import_api -y

#script:
  - phpunit -c ./core/phpunit.xml.dist $MODULE_DIR
