<?php

/**
 * @file
 * Contains import_api.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function import_api_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the import_api module.
    case 'help.page.import_api':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Lets you build importers that can be run trough the Drupal interface or during cron runs.') . '</p>';
      return $output;

    default:
  }
}
