<?php

namespace Drupal\import_api\Plugin\Derivative;

use Drupal\Component\Plugin\Derivative\DeriverBase;

class ImporterQueueDeriver extends DeriverBase {

  public function getDerivativeDefinitions($base_plugin_definition)
  {
    return parent::getDerivativeDefinitions($base_plugin_definition); // TODO: Change the autogenerated stub
  }
}
